<?php

namespace Database\Seeders;

use App\Models\KpiDefinition;
use Illuminate\Database\Seeder;

class KpiDefinitionSeeder extends Seeder
{
    public function run(): void
    {
        $definitions = [

            // ── Business Development ──────────────────────────────────────────
            [
                'code'               => 'BD_ACCOUNTS_OPENED',
                'name'               => 'Accounts Opened',
                'description'        => 'Number of new deposit/savings/current accounts opened by the officer in the period.',
                'category'           => 'business_development',
                'unit'               => 'count',
                'direction'          => 'higher_better',
                'weight'             => 1.50,
                'department_applicable' => ['marketing', 'operations', 'branch'],
                'computation_type'   => 'auto',
                'auto_compute_method'=> 'accounts_opened',
                'is_system'          => true,
            ],
            [
                'code'               => 'BD_DEPOSIT_MOBILIZATION',
                'name'               => 'Deposit Mobilization (₦)',
                'description'        => 'Total current balance of active accounts opened by the officer.',
                'category'           => 'business_development',
                'unit'               => 'ngn',
                'direction'          => 'higher_better',
                'weight'             => 2.00,
                'department_applicable' => ['marketing', 'branch'],
                'computation_type'   => 'auto',
                'auto_compute_method'=> 'deposit_mobilization',
                'is_system'          => true,
            ],
            [
                'code'               => 'BD_CROSS_SELL_RATIO',
                'name'               => 'Cross-sell Ratio (%)',
                'description'        => 'Percentage of the officer\'s loan customers who also hold an active savings account. CGAP standard.',
                'category'           => 'business_development',
                'unit'               => 'percent',
                'direction'          => 'higher_better',
                'weight'             => 1.00,
                'department_applicable' => ['marketing', 'credit', 'branch'],
                'computation_type'   => 'auto',
                'auto_compute_method'=> 'cross_sell_ratio',
                'is_system'          => true,
            ],
            [
                'code'               => 'BD_CUSTOMER_RETENTION',
                'name'               => 'Customer Retention Rate (%)',
                'description'        => 'Percentage of customers still active at end of period vs start. Manual entry required.',
                'category'           => 'business_development',
                'unit'               => 'percent',
                'direction'          => 'higher_better',
                'weight'             => 1.00,
                'department_applicable' => null,
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],

            // ── Credit & Lending ──────────────────────────────────────────────
            [
                'code'               => 'CL_LOANS_COUNT',
                'name'               => 'Loans Disbursed (Count)',
                'description'        => 'Number of loans disbursed by the officer in the period. CBN MFB quarterly return metric.',
                'category'           => 'credit_lending',
                'unit'               => 'count',
                'direction'          => 'higher_better',
                'weight'             => 2.00,
                'department_applicable' => ['credit', 'branch'],
                'computation_type'   => 'auto',
                'auto_compute_method'=> 'loans_count',
                'is_system'          => true,
            ],
            [
                'code'               => 'CL_LOANS_VALUE',
                'name'               => 'Loans Disbursed (₦)',
                'description'        => 'Total principal value of loans disbursed by the officer in the period.',
                'category'           => 'credit_lending',
                'unit'               => 'ngn',
                'direction'          => 'higher_better',
                'weight'             => 2.00,
                'department_applicable' => ['credit', 'branch'],
                'computation_type'   => 'auto',
                'auto_compute_method'=> 'loans_value',
                'is_system'          => true,
            ],
            [
                'code'               => 'CL_PAR30',
                'name'               => 'PAR 30 (%)',
                'description'        => 'Portfolio at Risk >30 days: outstanding balance of loans 30+ DPD / total portfolio. CGAP standard; CBN MFB target <5%.',
                'category'           => 'credit_lending',
                'unit'               => 'percent',
                'direction'          => 'lower_better',
                'weight'             => 3.00,
                'department_applicable' => ['credit', 'branch'],
                'computation_type'   => 'auto',
                'auto_compute_method'=> 'par30',
                'is_system'          => true,
            ],
            [
                'code'               => 'CL_PAR60',
                'name'               => 'PAR 60 (%)',
                'description'        => 'Portfolio at Risk >60 days. Indicates emerging credit quality issues.',
                'category'           => 'credit_lending',
                'unit'               => 'percent',
                'direction'          => 'lower_better',
                'weight'             => 2.50,
                'department_applicable' => ['credit', 'branch'],
                'computation_type'   => 'auto',
                'auto_compute_method'=> 'par60',
                'is_system'          => true,
            ],
            [
                'code'               => 'CL_PAR90',
                'name'               => 'PAR 90 (%)',
                'description'        => 'Portfolio at Risk >90 days. Maps to CBN Substandard + Doubtful + Loss classification bands.',
                'category'           => 'credit_lending',
                'unit'               => 'percent',
                'direction'          => 'lower_better',
                'weight'             => 3.00,
                'department_applicable' => ['credit', 'branch'],
                'computation_type'   => 'auto',
                'auto_compute_method'=> 'par90',
                'is_system'          => true,
            ],
            [
                'code'               => 'CL_COLLECTION_EFFICIENCY',
                'name'               => 'Collection Efficiency (%)',
                'description'        => 'Repayments received / amounts due in period × 100. CGAP benchmark: >95% for healthy MFB.',
                'category'           => 'credit_lending',
                'unit'               => 'percent',
                'direction'          => 'higher_better',
                'weight'             => 3.00,
                'department_applicable' => ['credit', 'collections', 'branch'],
                'computation_type'   => 'auto',
                'auto_compute_method'=> 'collection_efficiency',
                'is_system'          => true,
            ],
            [
                'code'               => 'CL_DISBURSEMENT_TAT',
                'name'               => 'Disbursement TAT (days)',
                'description'        => 'Average days from loan application to disbursement. Lower = faster service delivery.',
                'category'           => 'credit_lending',
                'unit'               => 'days',
                'direction'          => 'lower_better',
                'weight'             => 1.50,
                'department_applicable' => ['credit'],
                'computation_type'   => 'auto',
                'auto_compute_method'=> 'disbursement_tat',
                'is_system'          => true,
            ],
            [
                'code'               => 'CL_WRITE_OFF_RATIO',
                'name'               => 'Write-off Ratio (%)',
                'description'        => 'Total loans written off / total portfolio × 100. CBN Prudential Guidelines metric.',
                'category'           => 'credit_lending',
                'unit'               => 'percent',
                'direction'          => 'lower_better',
                'weight'             => 2.00,
                'department_applicable' => ['credit', 'branch'],
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],
            [
                'code'               => 'CL_LOAN_RENEWAL_RATE',
                'name'               => 'Loan Renewal Rate (%)',
                'description'        => 'Percentage of closed loans that were renewed/reborrowed by the same customer. CGAP sustainability metric.',
                'category'           => 'credit_lending',
                'unit'               => 'percent',
                'direction'          => 'higher_better',
                'weight'             => 1.00,
                'department_applicable' => ['credit'],
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],

            // ── Operations ───────────────────────────────────────────────────
            [
                'code'               => 'OPS_TXN_VOLUME',
                'name'               => 'Transactions Processed (Count)',
                'description'        => 'Total number of transactions processed by the officer/branch in the period.',
                'category'           => 'operations',
                'unit'               => 'count',
                'direction'          => 'higher_better',
                'weight'             => 1.00,
                'department_applicable' => ['operations', 'branch'],
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],
            [
                'code'               => 'OPS_KYC_COMPLETION',
                'name'               => 'KYC Completion Rate (%)',
                'description'        => 'Percentage of customers with fully completed KYC documentation. CBN KYC Circular requirement.',
                'category'           => 'operations',
                'unit'               => 'percent',
                'direction'          => 'higher_better',
                'weight'             => 1.50,
                'department_applicable' => ['operations', 'compliance', 'branch'],
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],
            [
                'code'               => 'OPS_SLA_COMPLIANCE',
                'name'               => 'Workflow SLA Compliance (%)',
                'description'        => 'Percentage of workflows/tasks completed within SLA deadlines.',
                'category'           => 'operations',
                'unit'               => 'percent',
                'direction'          => 'higher_better',
                'weight'             => 1.00,
                'department_applicable' => ['operations'],
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],
            [
                'code'               => 'OPS_ERROR_RATE',
                'name'               => 'Error / Reversal Rate (%)',
                'description'        => 'Percentage of transactions reversed or corrected. Basel III operational risk indicator.',
                'category'           => 'operations',
                'unit'               => 'percent',
                'direction'          => 'lower_better',
                'weight'             => 1.00,
                'department_applicable' => ['operations'],
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],

            // ── Customer Service ──────────────────────────────────────────────
            [
                'code'               => 'CS_COMPLAINTS_RESOLVED',
                'name'               => 'Complaints Resolved (%)',
                'description'        => 'Percentage of customer complaints resolved in the period. CBN Consumer Protection Framework.',
                'category'           => 'customer_service',
                'unit'               => 'percent',
                'direction'          => 'higher_better',
                'weight'             => 1.50,
                'department_applicable' => null,
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],
            [
                'code'               => 'CS_COMPLAINT_TAT',
                'name'               => 'Complaint Resolution TAT (days)',
                'description'        => 'Average days to resolve a customer complaint. CBN mandates ≤2 business days.',
                'category'           => 'customer_service',
                'unit'               => 'days',
                'direction'          => 'lower_better',
                'weight'             => 1.50,
                'department_applicable' => null,
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],
            [
                'code'               => 'CS_SATISFACTION_SCORE',
                'name'               => 'Customer Satisfaction Score',
                'description'        => 'Average customer satisfaction rating (1–5 scale). CGAP outreach metric.',
                'category'           => 'customer_service',
                'unit'               => 'score',
                'direction'          => 'higher_better',
                'weight'             => 1.00,
                'department_applicable' => null,
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],

            // ── Branch Performance ────────────────────────────────────────────
            [
                'code'               => 'BR_LOAN_PORTFOLIO',
                'name'               => 'Branch Loan Portfolio (₦)',
                'description'        => 'Total outstanding loan balance for the branch. CBN branch-level return metric.',
                'category'           => 'branch',
                'unit'               => 'ngn',
                'direction'          => 'higher_better',
                'weight'             => 2.00,
                'department_applicable' => ['branch'],
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],
            [
                'code'               => 'BR_DEPOSIT_PORTFOLIO',
                'name'               => 'Branch Deposit Portfolio (₦)',
                'description'        => 'Total deposit liabilities of the branch.',
                'category'           => 'branch',
                'unit'               => 'ngn',
                'direction'          => 'higher_better',
                'weight'             => 2.00,
                'department_applicable' => ['branch'],
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],
            [
                'code'               => 'BR_OSS',
                'name'               => 'Operational Self-Sufficiency (%)',
                'description'        => 'Financial revenue / total operating expense × 100. CGAP: >100% = financially viable branch.',
                'category'           => 'branch',
                'unit'               => 'percent',
                'direction'          => 'higher_better',
                'weight'             => 2.00,
                'department_applicable' => ['branch'],
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],
            [
                'code'               => 'BR_STAFF_PRODUCTIVITY',
                'name'               => 'Staff Productivity (Loans/Officer)',
                'description'        => 'Average number of active loans per credit officer in the branch. CGAP benchmark: >100 per officer.',
                'category'           => 'branch',
                'unit'               => 'count',
                'direction'          => 'higher_better',
                'weight'             => 1.00,
                'department_applicable' => ['branch'],
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],
            [
                'code'               => 'BR_NEW_CUSTOMERS',
                'name'               => 'New Customers Acquired',
                'description'        => 'Number of new customers onboarded by the branch in the period.',
                'category'           => 'branch',
                'unit'               => 'count',
                'direction'          => 'higher_better',
                'weight'             => 1.50,
                'department_applicable' => ['branch', 'marketing'],
                'computation_type'   => 'manual',
                'auto_compute_method'=> null,
                'is_system'          => true,
            ],
        ];

        foreach ($definitions as $def) {
            KpiDefinition::updateOrCreate(
                ['code' => $def['code']],
                array_merge($def, ['tenant_id' => null, 'is_active' => true])
            );
        }

        $this->command->info('Seeded ' . count($definitions) . ' system KPI definitions.');
    }
}
