[program:bankos-queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/bankos/artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/bankos/worker-default.log
stopwaitsecs=3600

[program:bankos-queue-transfers]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/bankos/artisan queue:work --queue=transfers --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=www-data
numprocs=4
redirect_stderr=true
stdout_logfile=/var/log/bankos/worker-transfers.log
stopwaitsecs=3600

[program:bankos-queue-notifications]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/bankos/artisan queue:work --queue=notifications --sleep=3 --tries=5 --max-time=3600
autostart=true
autorestart=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/bankos/worker-notifications.log
stopwaitsecs=3600

[program:bankos-queue-pdf]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/bankos/artisan queue:work --queue=pdf --sleep=5 --tries=2 --max-time=3600
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/bankos/worker-pdf.log
stopwaitsecs=3600

[program:bankos-queue-aml]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/bankos/artisan queue:work --queue=aml --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/bankos/worker-aml.log
stopwaitsecs=3600

[program:bankos-queue-webhooks]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/bankos/artisan queue:work --queue=webhooks --sleep=3 --tries=5 --max-time=3600
autostart=true
autorestart=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/bankos/worker-webhooks.log
stopwaitsecs=3600

[group:bankos-workers]
programs=bankos-queue-default,bankos-queue-transfers,bankos-queue-notifications,bankos-queue-pdf,bankos-queue-aml,bankos-queue-webhooks
